
services:
  db-service:
    build: db-service
    ports:
      - '8000:8000'
    volumes:
      - ./db-service:/code
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - "RECOMMENDER_HOST=recommender"

  aggregator:
    build: aggregator
    ports:
      - '8010:8010'
    volumes:
      - ./aggregator:/code
    depends_on:
      db-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8010"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - "DB_HOST=db-service"
      - "LLM_HOST=llm"
      - "RECOMMENDER_HOST=recommender"
      - "SCRAPER_HOST=scraper"
      - "OLLAMA_HOST=ollama"
      - "RUN_FIRST=false"
      - "RUN_WORKFLOW=false"

  bundler:
    build: bundler
    ports:
      - '8020:8020'
    volumes:
      - ./bundler:/code
    depends_on:
      db-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8020"]
      interval: 15s
      timeout: 10s
      retries: 5
    environment:
      - "DB_HOST=db-service"
      - "LLM_HOST=llm"
      - "RECOMMENDER_HOST=recommender"
      - "SCRAPER_HOST=scraper"
      - "OLLAMA_HOST=ollama"
      - "SUBSCRIBER_IP=bundler"
      - "PUBLISHER_IP=aggregator"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true

  recommender:
    build: recommender
    ports:
      - '8030:8030'
    volumes:
      - ./recommender:/code
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      - "DB_HOST=db-service"
      - "LLM_HOST=llm"
      - "RECOMMENDER_HOST=recommender"
      - "SCRAPER_HOST=scraper"
      - "OLLAMA_HOST=ollama"
    tty: true
    stdin_open: true

  llm:
    build: llm
    ports:
      - '8040:8040'
    volumes:
      - ./llm:/code
    depends_on:
      db-service:
        condition: service_healthy
      ollama:
        condition: service_healthy
    environment:
      - "DB_HOST=db-service"
      - "LLM_HOST=llm"
      - "RECOMMENDER_HOST=recommender"
      - "SCRAPER_HOST=scraper"
      - "OLLAMA_HOST=ollama"
    tty: true
    stdin_open: true

  scraper:
    build: scraper
    ports:
      - '8050:8050'
    volumes:
      - ./scraper:/code
    depends_on:
      db-service:
        condition: service_healthy
    environment:
      - "DB_HOST=db-service"
      - "LLM_HOST=llm"
      - "RECOMMENDER_HOST=recommender"
      - "SCRAPER_HOST=scraper"
      - "OLLAMA_HOST=ollama"
    tty: true
    stdin_open: true

  news-aggregator-frontend:
    build: news-aggregator-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./news-aggregator-frontend:/code
      - /code/node_modules
    depends_on:
      db-service:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ./ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "bash", "-c", "cat", "<", "/dev/null", ">", "/dev/tcp/localhost/11434"]
      interval: 15s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - "OLLAMA_HOST=0.0.0.0"